name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Login to Docker Hub
    - name: Login to Docker Hub
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dacn:latest .

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dacn:latest

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: self-hosted

    steps:
    # Step 1: Pull the latest Docker image
    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dacn:latest

    # Step 2: Stop and remove the old container
    - name: Stop and remove old container
      run: |
        sudo docker stop dacn-container || true
        sudo docker rm dacn-container || true

    # Step 3: Run the new Docker container

    - name: Create .env file
      run: |
        cat > .env <<EOF
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        DATABASE_USER=${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME=${{ secrets.DATABASE_NAME }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}
        S3_BUCKET=${{ secrets.S3_BUCKET }}
        S3_REGION=${{ secrets.S3_REGION }}
        GCS_PROJECT_ID=${{ secrets.GCS_PROJECT_ID }}
        GCS_BUCKET=${{ secrets.GCS_BUCKET }}
        GCS_PRESIGN_EXPIRES=${{ secrets.GCS_PRESIGN_EXPIRES }}
        GCS_PUBLIC_BASE_URL=${{ secrets.GCS_PUBLIC_BASE_URL }}
        GCS_CLIENT_EMAIL=${{ secrets.GCS_CLIENT_EMAIL }}
        GCS_PRIVATE_KEY=${{ secrets.GCS_PRIVATE_KEY }}
        EOF

    - name: Run new container
      run: |
          docker run -d \
            --name dacn-container \
            -p 3000:3000 \
            --env-file .env \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/dacn:latest

    - name: Cleanup unused images
      run: docker image prune -f
